name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_PREFIX: job-notification-bot

jobs:
  # Build and push each module (parallelized)
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [notifier, router, subscriber-bot]
    steps:
      - uses: actions/checkout@v4

      - if: matrix.module == 'notifier'
        name: Import parsers implementation (only notifier)
        working-directory: ./notifier/src/main/java/com/github/yehortpk/notifier/entities/
        run: apt update && apt install unzip wget && wget -O companies.zip ${{ secrets.COMPANIES_PARSER_IMPLEMENTATION_URL }} && unzip companies.zip

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Maven build and test
        working-directory: ./${{ matrix.module }}
        run: mvn clean install test

      - name: Build Docker image
        working-directory: ./${{ matrix.module }}
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_PREFIX-${{ matrix.module }} -f prod.Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_PREFIX-${{ matrix.module }}
