name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_PREFIX: job-notification-bot

jobs:
  # Build and push each module (parallelized)
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [notifier, router, subscriber-bot]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build JAR
        working-directory: ./${{ matrix.module }}
        run: mvn clean install -DskipTests

      # Temporarily remove
      #      - name: Run tests
      #        working-directory: ./${{ matrix.module }}
      #        run: mvn test

      - name: Build Docker image
        working-directory: ./${{ matrix.module }}
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_PREFIX-${{ matrix.module }} -f prod.Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_PREFIX-${{ matrix.module }}
